### ISSUE TITLE
wrapAsJSONCompatible method not found

### ISSUE THREAD

**Issue by erickyi2006** [EclairJS/eclairjs-nashorn#306]
I just cloned the latest from git and run mvn package

I got the following errors. Any idea?
[ERROR] /C:/Tools/eclairjs-nashorn/src/main/java/org/eclairjs/nashorn/Utils.java:[430,48] cannot find symbol
  symbol:   method wrapAsJSONCompatible(java.lang.Object,<nulltype>)
  location: class jdk.nashorn.api.scripting.ScriptObjectMirror
[ERROR] /C:/Tools/eclairjs-nashorn/src/main/java/org/eclairjs/nashorn/Utils.java:[435,56] incompatible types: java.lang.Object cannot be converted to jdk.nash
[ERROR] /C:/Tools/eclairjs-nashorn/src/main/java/org/eclairjs/nashorn/Utils.java:[507,34] cannot find symbol
  symbol:   method wrapAsJSONCompatible(java.lang.Object,<nulltype>)
  location: class jdk.nashorn.api.scripting.ScriptObjectMirror
[INFO] 3 errors

**Comment by erickyi2006** [comment]
Please ignore. I found the issue. I was on Java 8u25 and ScriptObjectMirror is only available since 8u40. 
Updating my Java now and will post results soon

**Comment by erickyi2006** [comment]
Status Update after updating my Java to 8u102
Passed through the compilation stage
But failed the unit test stage and no dlls or jars created. I am thinking aloud : is this supported in Windows? If not, I will move my development environment to Linux. Any hint or pointer to the right direction is most appreciated.

Tests run: 265, Failures: 8, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:35 min
[INFO] Finished at: 2016-08-15T11:22:36+10:00
[INFO] Final Memory: 24M/437M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project eclairjs-nashorn: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Tools\eclairjs-nashorn\target\surefire-reports for the individual test results.

**Comment by billreed63** [comment]
You are the first I am aware of trying on Windows, but it should run. What test cases are failing and how are they failing?
